// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


/// Availability of the OS built-in model. Mirrors
/// `flutter_gemma_builtin_ai`'s `AvailabilityStatus` one-to-one so the bridge
/// can map it across without a lookup table.
enum AvailabilityStatus {
  available,
  downloadable,
  downloading,
  unavailableDeviceUnsupported,
  unavailableOsTooOld,
  /// The feature exists but the user turned it off — Apple Intelligence in
  /// Settings, or the AICore/Gemini Nano toggle on Android.
  unavailableDisabled,
  unavailableOther,
}

/// Which OS API is answering. `unsupported` is the honest answer on a platform
/// with no built-in model rather than a guess.
enum LocalAiBackend {
  androidMlKitGenAi,
  appleFoundationModels,
  windowsAiFoundry,
  /// Windows AI Foundry is present but the plugin was built without the
  /// Windows AI SDK headers, so no inference can run.
  windowsAiFoundryUnconfigured,
  chromePromptApi,
  unsupported,
}

enum ToolArgumentKind {
  string,
  integer,
  number,
  boolean,
}

/// What the *running* host can actually do. Every field is a runtime property
/// of this device + OS + build, never a compile-time assumption: the same
/// binary reports `supportsVision: false` on iOS 26 and `true` on iOS 27.
class LocalAiBackendInfo {
  LocalAiBackendInfo({
    required this.backend,
    required this.platform,
    required this.apiName,
    required this.supportsToolCalling,
    required this.supportsStructuredOutput,
    required this.supportsVision,
    required this.supportsTokenCount,
    required this.supportsModelDownload,
    required this.supportsPlayStoreRedirect,
    required this.isConfigured,
  });

  LocalAiBackend backend;

  String platform;

  String apiName;

  /// Native function calling (Apple `Tool`). False where tool use has to be
  /// woven into the prompt instead.
  bool supportsToolCalling;

  /// Generation constrained to a JSON schema (Apple `GenerationSchema`,
  /// Chrome's `responseConstraint`).
  bool supportsStructuredOutput;

  bool supportsVision;

  /// A real tokenizer is reachable, so `countTokens` is exact rather than a
  /// character heuristic.
  bool supportsTokenCount;

  bool supportsModelDownload;

  bool supportsPlayStoreRedirect;

  /// The backend is present AND this build can drive it.
  bool isConfigured;

  List<Object?> _toList() {
    return <Object?>[
      backend,
      platform,
      apiName,
      supportsToolCalling,
      supportsStructuredOutput,
      supportsVision,
      supportsTokenCount,
      supportsModelDownload,
      supportsPlayStoreRedirect,
      isConfigured,
    ];
  }

  Object encode() {
    return _toList();  }

  static LocalAiBackendInfo decode(Object result) {
    result as List<Object?>;
    return LocalAiBackendInfo(
      backend: result[0]! as LocalAiBackend,
      platform: result[1]! as String,
      apiName: result[2]! as String,
      supportsToolCalling: result[3]! as bool,
      supportsStructuredOutput: result[4]! as bool,
      supportsVision: result[5]! as bool,
      supportsTokenCount: result[6]! as bool,
      supportsModelDownload: result[7]! as bool,
      supportsPlayStoreRedirect: result[8]! as bool,
      isConfigured: result[9]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LocalAiBackendInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class ToolParameterSpec {
  ToolParameterSpec({
    required this.name,
    required this.kind,
    required this.optional,
    this.description,
  });

  String name;

  ToolArgumentKind kind;

  bool optional;

  String? description;

  List<Object?> _toList() {
    return <Object?>[
      name,
      kind,
      optional,
      description,
    ];
  }

  Object encode() {
    return _toList();  }

  static ToolParameterSpec decode(Object result) {
    result as List<Object?>;
    return ToolParameterSpec(
      name: result[0]! as String,
      kind: result[1]! as ToolArgumentKind,
      optional: result[2]! as bool,
      description: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ToolParameterSpec || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Per-call sampling overrides.
///
/// A session fixes its sampling at creation, which is what flutter_gemma's
/// engine contract expects. Both Apple `respond(options:)` and ML Kit's
/// request builder also accept options per request, though, and the
/// prompt-oriented Dart API applies a `GenerationConfig` to a single call
/// without disturbing the conversation. Every field is nullable: null means
/// "keep what the session was created with".
class GenerationOverrides {
  GenerationOverrides({
    this.temperature,
    this.topP,
    this.topK,
    this.maxOutputTokens,
  });

  double? temperature;

  double? topP;

  int? topK;

  int? maxOutputTokens;

  List<Object?> _toList() {
    return <Object?>[
      temperature,
      topP,
      topK,
      maxOutputTokens,
    ];
  }

  Object encode() {
    return _toList();  }

  static GenerationOverrides decode(Object result) {
    result as List<Object?>;
    return GenerationOverrides(
      temperature: result[0] as double?,
      topP: result[1] as double?,
      topK: result[2] as int?,
      maxOutputTokens: result[3] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GenerationOverrides || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class ToolSpec {
  ToolSpec({
    required this.name,
    required this.description,
    required this.parameters,
  });

  String name;

  String description;

  List<ToolParameterSpec> parameters;

  List<Object?> _toList() {
    return <Object?>[
      name,
      description,
      parameters,
    ];
  }

  Object encode() {
    return _toList();  }

  static ToolSpec decode(Object result) {
    result as List<Object?>;
    return ToolSpec(
      name: result[0]! as String,
      description: result[1]! as String,
      parameters: (result[2] as List<Object?>?)!.cast<ToolParameterSpec>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ToolSpec || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is AvailabilityStatus) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is LocalAiBackend) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is ToolArgumentKind) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is LocalAiBackendInfo) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is ToolParameterSpec) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is GenerationOverrides) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is ToolSpec) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : AvailabilityStatus.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : LocalAiBackend.values[value];
      case 131: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : ToolArgumentKind.values[value];
      case 132: 
        return LocalAiBackendInfo.decode(readValue(buffer)!);
      case 133: 
        return ToolParameterSpec.decode(readValue(buffer)!);
      case 134: 
        return GenerationOverrides.decode(readValue(buffer)!);
      case 135: 
        return ToolSpec.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class LocalAiService {
  /// Constructor for [LocalAiService].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LocalAiService({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<AvailabilityStatus> checkAvailability() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_local_ai.LocalAiService.checkAvailability$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as AvailabilityStatus?)!;
    }
  }

  /// One human-readable sentence naming what the user would have to change —
  /// enable Apple Intelligence, update the OS, use an eligible device. Shown
  /// in UI, so it is prose, not a status code.
  Future<String> availabilityReason() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_local_ai.LocalAiService.availabilityReason$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<LocalAiBackendInfo> getBackendInfo() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_local_ai.LocalAiService.getBackendInfo$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as LocalAiBackendInfo?)!;
    }
  }

  /// Starts the OS feature download (AICore). Progress arrives on the event
  /// channel as `{code: DOWNLOAD_PROGRESS, bytesDownloaded, bytesTotal}`.
  /// No-op on darwin, where readiness is user-controlled in Settings.
  Future<void> downloadFeature() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_local_ai.LocalAiService.downloadFeature$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Opens Google AICore in the Play Store. False on every non-Android host.
  Future<bool> openAICorePlayStore() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_local_ai.LocalAiService.openAICorePlayStore$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<void> createModel({required bool supportImage}) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_local_ai.LocalAiService.createModel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[supportImage]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> closeModel() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_local_ai.LocalAiService.closeModel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Sessions are keyed by a caller-allocated [sessionId]; every generated
  /// token on the event channel carries it back so concurrent sessions can be
  /// demultiplexed.
  ///
  /// [tools] must be supplied here rather than per-request: Apple binds tools
  /// at `LanguageModelSession` construction and cannot add them to a live
  /// session.
  Future<void> createSession({required int sessionId, required double temperature, required int topK, double? topP, int? maxOutputTokens, String? systemInstruction, List<ToolSpec>? tools, }) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_local_ai.LocalAiService.createSession$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId, temperature, topK, topP, maxOutputTokens, systemInstruction, tools]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> closeSession(int sessionId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_local_ai.LocalAiService.closeSession$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> addQueryChunk({required int sessionId, required String text}) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_local_ai.LocalAiService.addQueryChunk$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId, text]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> addImage({required int sessionId, required Uint8List imageBytes}) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_local_ai.LocalAiService.addImage$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId, imageBytes]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<String> generateResponse(int sessionId, GenerationOverrides? overrides) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_local_ai.LocalAiService.generateResponse$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId, overrides]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  /// Streams the response; tokens arrive on the event channel as
  /// `{sessionId, partialResult, done}` and failures as
  /// `{sessionId, code: ERROR, message}`.
  Future<void> generateResponseAsync(int sessionId, GenerationOverrides? overrides) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_local_ai.LocalAiService.generateResponseAsync$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId, overrides]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Generation constrained to [schemaJson] (a JSON Schema document). Hosts
  /// reporting `supportsStructuredOutput: false` fail this call rather than
  /// silently returning prose.
  Future<String> generateStructuredResponse({required int sessionId, required String schemaJson, GenerationOverrides? overrides, }) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_local_ai.LocalAiService.generateStructuredResponse$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId, schemaJson, overrides]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<void> stopGeneration(int sessionId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_local_ai.LocalAiService.stopGeneration$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Exact token count where the host has a tokenizer. Hosts reporting
  /// `supportsTokenCount: false` fail with `TOKENIZER_UNAVAILABLE`, which the
  /// Dart layer turns into a documented character-based estimate.
  Future<int> countTokens(String text) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_local_ai.LocalAiService.countTokens$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[text]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }
}

/// Host → Dart callback for native tool calling. The host suspends generation,
/// asks Dart to run the tool, and feeds the result back to the model.
abstract class LocalAiToolRunner {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// [argumentsJson] is a JSON object of the arguments the model produced.
  /// Returns the tool's result encoded as JSON, or null when the tool yields
  /// nothing.
  Future<String?> onToolCall(int sessionId, String toolName, String argumentsJson);

  static void setUp(LocalAiToolRunner? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_local_ai.LocalAiToolRunner.onToolCall$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_local_ai.LocalAiToolRunner.onToolCall was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_sessionId = (args[0] as int?);
          assert(arg_sessionId != null,
              'Argument for dev.flutter.pigeon.flutter_local_ai.LocalAiToolRunner.onToolCall was null, expected non-null int.');
          final String? arg_toolName = (args[1] as String?);
          assert(arg_toolName != null,
              'Argument for dev.flutter.pigeon.flutter_local_ai.LocalAiToolRunner.onToolCall was null, expected non-null String.');
          final String? arg_argumentsJson = (args[2] as String?);
          assert(arg_argumentsJson != null,
              'Argument for dev.flutter.pigeon.flutter_local_ai.LocalAiToolRunner.onToolCall was null, expected non-null String.');
          try {
            final String? output = await api.onToolCall(arg_sessionId!, arg_toolName!, arg_argumentsJson!);
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
