// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "local_ai_pigeon.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace flutter_local_ai_pigeon {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

// LocalAiBackendInfo

LocalAiBackendInfo::LocalAiBackendInfo(
  const LocalAiBackend& backend,
  const std::string& platform,
  const std::string& api_name,
  bool supports_tool_calling,
  bool supports_structured_output,
  bool supports_vision,
  bool supports_token_count,
  bool supports_model_download,
  bool supports_play_store_redirect,
  bool is_configured)
 : backend_(backend),
    platform_(platform),
    api_name_(api_name),
    supports_tool_calling_(supports_tool_calling),
    supports_structured_output_(supports_structured_output),
    supports_vision_(supports_vision),
    supports_token_count_(supports_token_count),
    supports_model_download_(supports_model_download),
    supports_play_store_redirect_(supports_play_store_redirect),
    is_configured_(is_configured) {}

const LocalAiBackend& LocalAiBackendInfo::backend() const {
  return backend_;
}

void LocalAiBackendInfo::set_backend(const LocalAiBackend& value_arg) {
  backend_ = value_arg;
}


const std::string& LocalAiBackendInfo::platform() const {
  return platform_;
}

void LocalAiBackendInfo::set_platform(std::string_view value_arg) {
  platform_ = value_arg;
}


const std::string& LocalAiBackendInfo::api_name() const {
  return api_name_;
}

void LocalAiBackendInfo::set_api_name(std::string_view value_arg) {
  api_name_ = value_arg;
}


bool LocalAiBackendInfo::supports_tool_calling() const {
  return supports_tool_calling_;
}

void LocalAiBackendInfo::set_supports_tool_calling(bool value_arg) {
  supports_tool_calling_ = value_arg;
}


bool LocalAiBackendInfo::supports_structured_output() const {
  return supports_structured_output_;
}

void LocalAiBackendInfo::set_supports_structured_output(bool value_arg) {
  supports_structured_output_ = value_arg;
}


bool LocalAiBackendInfo::supports_vision() const {
  return supports_vision_;
}

void LocalAiBackendInfo::set_supports_vision(bool value_arg) {
  supports_vision_ = value_arg;
}


bool LocalAiBackendInfo::supports_token_count() const {
  return supports_token_count_;
}

void LocalAiBackendInfo::set_supports_token_count(bool value_arg) {
  supports_token_count_ = value_arg;
}


bool LocalAiBackendInfo::supports_model_download() const {
  return supports_model_download_;
}

void LocalAiBackendInfo::set_supports_model_download(bool value_arg) {
  supports_model_download_ = value_arg;
}


bool LocalAiBackendInfo::supports_play_store_redirect() const {
  return supports_play_store_redirect_;
}

void LocalAiBackendInfo::set_supports_play_store_redirect(bool value_arg) {
  supports_play_store_redirect_ = value_arg;
}


bool LocalAiBackendInfo::is_configured() const {
  return is_configured_;
}

void LocalAiBackendInfo::set_is_configured(bool value_arg) {
  is_configured_ = value_arg;
}


EncodableList LocalAiBackendInfo::ToEncodableList() const {
  EncodableList list;
  list.reserve(10);
  list.push_back(CustomEncodableValue(backend_));
  list.push_back(EncodableValue(platform_));
  list.push_back(EncodableValue(api_name_));
  list.push_back(EncodableValue(supports_tool_calling_));
  list.push_back(EncodableValue(supports_structured_output_));
  list.push_back(EncodableValue(supports_vision_));
  list.push_back(EncodableValue(supports_token_count_));
  list.push_back(EncodableValue(supports_model_download_));
  list.push_back(EncodableValue(supports_play_store_redirect_));
  list.push_back(EncodableValue(is_configured_));
  return list;
}

LocalAiBackendInfo LocalAiBackendInfo::FromEncodableList(const EncodableList& list) {
  LocalAiBackendInfo decoded(
    std::any_cast<const LocalAiBackend&>(std::get<CustomEncodableValue>(list[0])),
    std::get<std::string>(list[1]),
    std::get<std::string>(list[2]),
    std::get<bool>(list[3]),
    std::get<bool>(list[4]),
    std::get<bool>(list[5]),
    std::get<bool>(list[6]),
    std::get<bool>(list[7]),
    std::get<bool>(list[8]),
    std::get<bool>(list[9]));
  return decoded;
}

// ToolParameterSpec

ToolParameterSpec::ToolParameterSpec(
  const std::string& name,
  const ToolArgumentKind& kind,
  bool optional)
 : name_(name),
    kind_(kind),
    optional_(optional) {}

ToolParameterSpec::ToolParameterSpec(
  const std::string& name,
  const ToolArgumentKind& kind,
  bool optional,
  const std::string* description)
 : name_(name),
    kind_(kind),
    optional_(optional),
    description_(description ? std::optional<std::string>(*description) : std::nullopt) {}

const std::string& ToolParameterSpec::name() const {
  return name_;
}

void ToolParameterSpec::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


const ToolArgumentKind& ToolParameterSpec::kind() const {
  return kind_;
}

void ToolParameterSpec::set_kind(const ToolArgumentKind& value_arg) {
  kind_ = value_arg;
}


bool ToolParameterSpec::optional() const {
  return optional_;
}

void ToolParameterSpec::set_optional(bool value_arg) {
  optional_ = value_arg;
}


const std::string* ToolParameterSpec::description() const {
  return description_ ? &(*description_) : nullptr;
}

void ToolParameterSpec::set_description(const std::string_view* value_arg) {
  description_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void ToolParameterSpec::set_description(std::string_view value_arg) {
  description_ = value_arg;
}


EncodableList ToolParameterSpec::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(EncodableValue(name_));
  list.push_back(CustomEncodableValue(kind_));
  list.push_back(EncodableValue(optional_));
  list.push_back(description_ ? EncodableValue(*description_) : EncodableValue());
  return list;
}

ToolParameterSpec ToolParameterSpec::FromEncodableList(const EncodableList& list) {
  ToolParameterSpec decoded(
    std::get<std::string>(list[0]),
    std::any_cast<const ToolArgumentKind&>(std::get<CustomEncodableValue>(list[1])),
    std::get<bool>(list[2]));
  auto& encodable_description = list[3];
  if (!encodable_description.IsNull()) {
    decoded.set_description(std::get<std::string>(encodable_description));
  }
  return decoded;
}

// ToolSpec

ToolSpec::ToolSpec(
  const std::string& name,
  const std::string& description,
  const EncodableList& parameters)
 : name_(name),
    description_(description),
    parameters_(parameters) {}

const std::string& ToolSpec::name() const {
  return name_;
}

void ToolSpec::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


const std::string& ToolSpec::description() const {
  return description_;
}

void ToolSpec::set_description(std::string_view value_arg) {
  description_ = value_arg;
}


const EncodableList& ToolSpec::parameters() const {
  return parameters_;
}

void ToolSpec::set_parameters(const EncodableList& value_arg) {
  parameters_ = value_arg;
}


EncodableList ToolSpec::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(name_));
  list.push_back(EncodableValue(description_));
  list.push_back(EncodableValue(parameters_));
  return list;
}

ToolSpec ToolSpec::FromEncodableList(const EncodableList& list) {
  ToolSpec decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]),
    std::get<EncodableList>(list[2]));
  return decoded;
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<AvailabilityStatus>(enum_arg_value));
      }
    case 130: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<LocalAiBackend>(enum_arg_value));
      }
    case 131: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<ToolArgumentKind>(enum_arg_value));
      }
    case 132: {
        return CustomEncodableValue(LocalAiBackendInfo::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 133: {
        return CustomEncodableValue(ToolParameterSpec::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 134: {
        return CustomEncodableValue(ToolSpec::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(AvailabilityStatus)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<AvailabilityStatus>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(LocalAiBackend)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<LocalAiBackend>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(ToolArgumentKind)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<ToolArgumentKind>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(LocalAiBackendInfo)) {
      stream->WriteByte(132);
      WriteValue(EncodableValue(std::any_cast<LocalAiBackendInfo>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(ToolParameterSpec)) {
      stream->WriteByte(133);
      WriteValue(EncodableValue(std::any_cast<ToolParameterSpec>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(ToolSpec)) {
      stream->WriteByte(134);
      WriteValue(EncodableValue(std::any_cast<ToolSpec>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by LocalAiService.
const flutter::StandardMessageCodec& LocalAiService::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `LocalAiService` to handle messages through the `binary_messenger`.
void LocalAiService::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  LocalAiService* api) {
  LocalAiService::SetUp(binary_messenger, api, "");
}

void LocalAiService::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  LocalAiService* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.checkAvailability" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->CheckAvailability([reply](ErrorOr<AvailabilityStatus>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.availabilityReason" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->AvailabilityReason([reply](ErrorOr<std::string>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.getBackendInfo" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->GetBackendInfo([reply](ErrorOr<LocalAiBackendInfo>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.downloadFeature" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->DownloadFeature([reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.openAICorePlayStore" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->OpenAICorePlayStore([reply](ErrorOr<bool>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.createModel" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_support_image_arg = args.at(0);
          if (encodable_support_image_arg.IsNull()) {
            reply(WrapError("support_image_arg unexpectedly null."));
            return;
          }
          const auto& support_image_arg = std::get<bool>(encodable_support_image_arg);
          api->CreateModel(support_image_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.closeModel" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->CloseModel([reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.createSession" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_session_id_arg = args.at(0);
          if (encodable_session_id_arg.IsNull()) {
            reply(WrapError("session_id_arg unexpectedly null."));
            return;
          }
          const int64_t session_id_arg = encodable_session_id_arg.LongValue();
          const auto& encodable_temperature_arg = args.at(1);
          if (encodable_temperature_arg.IsNull()) {
            reply(WrapError("temperature_arg unexpectedly null."));
            return;
          }
          const auto& temperature_arg = std::get<double>(encodable_temperature_arg);
          const auto& encodable_top_k_arg = args.at(2);
          if (encodable_top_k_arg.IsNull()) {
            reply(WrapError("top_k_arg unexpectedly null."));
            return;
          }
          const int64_t top_k_arg = encodable_top_k_arg.LongValue();
          const auto& encodable_top_p_arg = args.at(3);
          const auto* top_p_arg = std::get_if<double>(&encodable_top_p_arg);
          const auto& encodable_max_output_tokens_arg = args.at(4);
          const auto* max_output_tokens_arg = std::get_if<int64_t>(&encodable_max_output_tokens_arg);
          const auto& encodable_system_instruction_arg = args.at(5);
          const auto* system_instruction_arg = std::get_if<std::string>(&encodable_system_instruction_arg);
          const auto& encodable_tools_arg = args.at(6);
          const auto* tools_arg = std::get_if<EncodableList>(&encodable_tools_arg);
          api->CreateSession(session_id_arg, temperature_arg, top_k_arg, top_p_arg, max_output_tokens_arg, system_instruction_arg, tools_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.closeSession" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_session_id_arg = args.at(0);
          if (encodable_session_id_arg.IsNull()) {
            reply(WrapError("session_id_arg unexpectedly null."));
            return;
          }
          const int64_t session_id_arg = encodable_session_id_arg.LongValue();
          api->CloseSession(session_id_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.addQueryChunk" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_session_id_arg = args.at(0);
          if (encodable_session_id_arg.IsNull()) {
            reply(WrapError("session_id_arg unexpectedly null."));
            return;
          }
          const int64_t session_id_arg = encodable_session_id_arg.LongValue();
          const auto& encodable_text_arg = args.at(1);
          if (encodable_text_arg.IsNull()) {
            reply(WrapError("text_arg unexpectedly null."));
            return;
          }
          const auto& text_arg = std::get<std::string>(encodable_text_arg);
          api->AddQueryChunk(session_id_arg, text_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.addImage" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_session_id_arg = args.at(0);
          if (encodable_session_id_arg.IsNull()) {
            reply(WrapError("session_id_arg unexpectedly null."));
            return;
          }
          const int64_t session_id_arg = encodable_session_id_arg.LongValue();
          const auto& encodable_image_bytes_arg = args.at(1);
          if (encodable_image_bytes_arg.IsNull()) {
            reply(WrapError("image_bytes_arg unexpectedly null."));
            return;
          }
          const auto& image_bytes_arg = std::get<std::vector<uint8_t>>(encodable_image_bytes_arg);
          api->AddImage(session_id_arg, image_bytes_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.generateResponse" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_session_id_arg = args.at(0);
          if (encodable_session_id_arg.IsNull()) {
            reply(WrapError("session_id_arg unexpectedly null."));
            return;
          }
          const int64_t session_id_arg = encodable_session_id_arg.LongValue();
          api->GenerateResponse(session_id_arg, [reply](ErrorOr<std::string>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.generateResponseAsync" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_session_id_arg = args.at(0);
          if (encodable_session_id_arg.IsNull()) {
            reply(WrapError("session_id_arg unexpectedly null."));
            return;
          }
          const int64_t session_id_arg = encodable_session_id_arg.LongValue();
          api->GenerateResponseAsync(session_id_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.generateStructuredResponse" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_session_id_arg = args.at(0);
          if (encodable_session_id_arg.IsNull()) {
            reply(WrapError("session_id_arg unexpectedly null."));
            return;
          }
          const int64_t session_id_arg = encodable_session_id_arg.LongValue();
          const auto& encodable_schema_json_arg = args.at(1);
          if (encodable_schema_json_arg.IsNull()) {
            reply(WrapError("schema_json_arg unexpectedly null."));
            return;
          }
          const auto& schema_json_arg = std::get<std::string>(encodable_schema_json_arg);
          api->GenerateStructuredResponse(session_id_arg, schema_json_arg, [reply](ErrorOr<std::string>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.stopGeneration" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_session_id_arg = args.at(0);
          if (encodable_session_id_arg.IsNull()) {
            reply(WrapError("session_id_arg unexpectedly null."));
            return;
          }
          const int64_t session_id_arg = encodable_session_id_arg.LongValue();
          api->StopGeneration(session_id_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.countTokens" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_text_arg = args.at(0);
          if (encodable_text_arg.IsNull()) {
            reply(WrapError("text_arg unexpectedly null."));
            return;
          }
          const auto& text_arg = std::get<std::string>(encodable_text_arg);
          api->CountTokens(text_arg, [reply](ErrorOr<int64_t>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue LocalAiService::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue LocalAiService::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

// Generated class from Pigeon that represents Flutter messages that can be called from C++.
LocalAiToolRunner::LocalAiToolRunner(flutter::BinaryMessenger* binary_messenger)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_("") {}

LocalAiToolRunner::LocalAiToolRunner(
  flutter::BinaryMessenger* binary_messenger,
  const std::string& message_channel_suffix)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_(message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "") {}

const flutter::StandardMessageCodec& LocalAiToolRunner::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

void LocalAiToolRunner::OnToolCall(
  int64_t session_id_arg,
  const std::string& tool_name_arg,
  const std::string& arguments_json_arg,
  std::function<void(const std::string*)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_local_ai.LocalAiToolRunner.onToolCall" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    EncodableValue(session_id_arg),
    EncodableValue(tool_name_arg),
    EncodableValue(arguments_json_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        const auto* return_value = std::get_if<std::string>(&list_return_value->at(0));
        on_success(return_value);
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

}  // namespace flutter_local_ai_pigeon
