// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_LOCAL_AI_PIGEON_G_H_
#define PIGEON_LOCAL_AI_PIGEON_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace flutter_local_ai_pigeon {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class LocalAiService;
  friend class LocalAiToolRunner;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


// Availability of the OS built-in model. Mirrors
// `flutter_gemma_builtin_ai`'s `AvailabilityStatus` one-to-one so the bridge
// can map it across without a lookup table.
enum class AvailabilityStatus {
  kAvailable = 0,
  kDownloadable = 1,
  kDownloading = 2,
  kUnavailableDeviceUnsupported = 3,
  kUnavailableOsTooOld = 4,
  // The feature exists but the user turned it off — Apple Intelligence in
  // Settings, or the AICore/Gemini Nano toggle on Android.
  kUnavailableDisabled = 5,
  kUnavailableOther = 6
};

// Which OS API is answering. `unsupported` is the honest answer on a platform
// with no built-in model rather than a guess.
enum class LocalAiBackend {
  kAndroidMlKitGenAi = 0,
  kAppleFoundationModels = 1,
  kWindowsAiFoundry = 2,
  // Windows AI Foundry is present but the plugin was built without the
  // Windows AI SDK headers, so no inference can run.
  kWindowsAiFoundryUnconfigured = 3,
  kChromePromptApi = 4,
  kUnsupported = 5
};

enum class ToolArgumentKind {
  kString = 0,
  kInteger = 1,
  kNumber = 2,
  kBoolean = 3
};


// What the *running* host can actually do. Every field is a runtime property
// of this device + OS + build, never a compile-time assumption: the same
// binary reports `supportsVision: false` on iOS 26 and `true` on iOS 27.
//
// Generated class from Pigeon that represents data sent in messages.
class LocalAiBackendInfo {
 public:
  // Constructs an object setting all fields.
  explicit LocalAiBackendInfo(
    const LocalAiBackend& backend,
    const std::string& platform,
    const std::string& api_name,
    bool supports_tool_calling,
    bool supports_structured_output,
    bool supports_vision,
    bool supports_token_count,
    bool supports_model_download,
    bool supports_play_store_redirect,
    bool is_configured);

  const LocalAiBackend& backend() const;
  void set_backend(const LocalAiBackend& value_arg);

  const std::string& platform() const;
  void set_platform(std::string_view value_arg);

  const std::string& api_name() const;
  void set_api_name(std::string_view value_arg);

  // Native function calling (Apple `Tool`). False where tool use has to be
  // woven into the prompt instead.
  bool supports_tool_calling() const;
  void set_supports_tool_calling(bool value_arg);

  // Generation constrained to a JSON schema (Apple `GenerationSchema`,
  // Chrome's `responseConstraint`).
  bool supports_structured_output() const;
  void set_supports_structured_output(bool value_arg);

  bool supports_vision() const;
  void set_supports_vision(bool value_arg);

  // A real tokenizer is reachable, so `countTokens` is exact rather than a
  // character heuristic.
  bool supports_token_count() const;
  void set_supports_token_count(bool value_arg);

  bool supports_model_download() const;
  void set_supports_model_download(bool value_arg);

  bool supports_play_store_redirect() const;
  void set_supports_play_store_redirect(bool value_arg);

  // The backend is present AND this build can drive it.
  bool is_configured() const;
  void set_is_configured(bool value_arg);

 private:
  static LocalAiBackendInfo FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class LocalAiService;
  friend class LocalAiToolRunner;
  friend class PigeonInternalCodecSerializer;
  LocalAiBackend backend_;
  std::string platform_;
  std::string api_name_;
  bool supports_tool_calling_;
  bool supports_structured_output_;
  bool supports_vision_;
  bool supports_token_count_;
  bool supports_model_download_;
  bool supports_play_store_redirect_;
  bool is_configured_;
};


// Generated class from Pigeon that represents data sent in messages.
class ToolParameterSpec {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit ToolParameterSpec(
    const std::string& name,
    const ToolArgumentKind& kind,
    bool optional);

  // Constructs an object setting all fields.
  explicit ToolParameterSpec(
    const std::string& name,
    const ToolArgumentKind& kind,
    bool optional,
    const std::string* description);

  const std::string& name() const;
  void set_name(std::string_view value_arg);

  const ToolArgumentKind& kind() const;
  void set_kind(const ToolArgumentKind& value_arg);

  bool optional() const;
  void set_optional(bool value_arg);

  const std::string* description() const;
  void set_description(const std::string_view* value_arg);
  void set_description(std::string_view value_arg);

 private:
  static ToolParameterSpec FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class LocalAiService;
  friend class LocalAiToolRunner;
  friend class PigeonInternalCodecSerializer;
  std::string name_;
  ToolArgumentKind kind_;
  bool optional_;
  std::optional<std::string> description_;
};


// Generated class from Pigeon that represents data sent in messages.
class ToolSpec {
 public:
  // Constructs an object setting all fields.
  explicit ToolSpec(
    const std::string& name,
    const std::string& description,
    const flutter::EncodableList& parameters);

  const std::string& name() const;
  void set_name(std::string_view value_arg);

  const std::string& description() const;
  void set_description(std::string_view value_arg);

  const flutter::EncodableList& parameters() const;
  void set_parameters(const flutter::EncodableList& value_arg);

 private:
  static ToolSpec FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class LocalAiService;
  friend class LocalAiToolRunner;
  friend class PigeonInternalCodecSerializer;
  std::string name_;
  std::string description_;
  flutter::EncodableList parameters_;
};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;
 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class LocalAiService {
 public:
  LocalAiService(const LocalAiService&) = delete;
  LocalAiService& operator=(const LocalAiService&) = delete;
  virtual ~LocalAiService() {}
  virtual void CheckAvailability(std::function<void(ErrorOr<AvailabilityStatus> reply)> result) = 0;
  // One human-readable sentence naming what the user would have to change —
  // enable Apple Intelligence, update the OS, use an eligible device. Shown
  // in UI, so it is prose, not a status code.
  virtual void AvailabilityReason(std::function<void(ErrorOr<std::string> reply)> result) = 0;
  virtual void GetBackendInfo(std::function<void(ErrorOr<LocalAiBackendInfo> reply)> result) = 0;
  // Starts the OS feature download (AICore). Progress arrives on the event
  // channel as `{code: DOWNLOAD_PROGRESS, bytesDownloaded, bytesTotal}`.
  // No-op on darwin, where readiness is user-controlled in Settings.
  virtual void DownloadFeature(std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Opens Google AICore in the Play Store. False on every non-Android host.
  virtual void OpenAICorePlayStore(std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void CreateModel(
    bool support_image,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void CloseModel(std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Sessions are keyed by a caller-allocated [sessionId]; every generated
  // token on the event channel carries it back so concurrent sessions can be
  // demultiplexed.
  //
  // [tools] must be supplied here rather than per-request: Apple binds tools
  // at `LanguageModelSession` construction and cannot add them to a live
  // session.
  virtual void CreateSession(
    int64_t session_id,
    double temperature,
    int64_t top_k,
    const double* top_p,
    const int64_t* max_output_tokens,
    const std::string* system_instruction,
    const flutter::EncodableList* tools,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void CloseSession(
    int64_t session_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void AddQueryChunk(
    int64_t session_id,
    const std::string& text,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void AddImage(
    int64_t session_id,
    const std::vector<uint8_t>& image_bytes,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void GenerateResponse(
    int64_t session_id,
    std::function<void(ErrorOr<std::string> reply)> result) = 0;
  // Streams the response; tokens arrive on the event channel as
  // `{sessionId, partialResult, done}` and failures as
  // `{sessionId, code: ERROR, message}`.
  virtual void GenerateResponseAsync(
    int64_t session_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Generation constrained to [schemaJson] (a JSON Schema document). Hosts
  // reporting `supportsStructuredOutput: false` fail this call rather than
  // silently returning prose.
  virtual void GenerateStructuredResponse(
    int64_t session_id,
    const std::string& schema_json,
    std::function<void(ErrorOr<std::string> reply)> result) = 0;
  virtual void StopGeneration(
    int64_t session_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Exact token count where the host has a tokenizer. Hosts reporting
  // `supportsTokenCount: false` fail with `TOKENIZER_UNAVAILABLE`, which the
  // Dart layer turns into a documented character-based estimate.
  virtual void CountTokens(
    const std::string& text,
    std::function<void(ErrorOr<int64_t> reply)> result) = 0;

  // The codec used by LocalAiService.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `LocalAiService` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    LocalAiService* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    LocalAiService* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  LocalAiService() = default;
};
// Host → Dart callback for native tool calling. The host suspends generation,
// asks Dart to run the tool, and feeds the result back to the model.
//
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class LocalAiToolRunner {
 public:
  LocalAiToolRunner(flutter::BinaryMessenger* binary_messenger);
  LocalAiToolRunner(
    flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const flutter::StandardMessageCodec& GetCodec();
  // [argumentsJson] is a JSON object of the arguments the model produced.
  // Returns the tool's result encoded as JSON, or null when the tool yields
  // nothing.
  void OnToolCall(
    int64_t session_id,
    const std::string& tool_name,
    const std::string& arguments_json,
    std::function<void(const std::string*)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
 private:
  flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace flutter_local_ai_pigeon
#endif  // PIGEON_LOCAL_AI_PIGEON_G_H_
