// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsLocalAiPigeon(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsLocalAiPigeon(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsLocalAiPigeon(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashLocalAiPigeon(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashLocalAiPigeon(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashLocalAiPigeon(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Availability of the OS built-in model. Mirrors
/// `flutter_gemma_builtin_ai`'s `AvailabilityStatus` one-to-one so the bridge
/// can map it across without a lookup table.
enum AvailabilityStatus: Int {
  case available = 0
  case downloadable = 1
  case downloading = 2
  case unavailableDeviceUnsupported = 3
  case unavailableOsTooOld = 4
  /// The feature exists but the user turned it off — Apple Intelligence in
  /// Settings, or the AICore/Gemini Nano toggle on Android.
  case unavailableDisabled = 5
  case unavailableOther = 6
}

/// Which OS API is answering. `unsupported` is the honest answer on a platform
/// with no built-in model rather than a guess.
enum LocalAiBackend: Int {
  case androidMlKitGenAi = 0
  case appleFoundationModels = 1
  case windowsAiFoundry = 2
  /// Windows AI Foundry is present but the plugin was built without the
  /// Windows AI SDK headers, so no inference can run.
  case windowsAiFoundryUnconfigured = 3
  case chromePromptApi = 4
  case unsupported = 5
}

enum ToolArgumentKind: Int {
  case string = 0
  case integer = 1
  case number = 2
  case boolean = 3
}

/// What the *running* host can actually do. Every field is a runtime property
/// of this device + OS + build, never a compile-time assumption: the same
/// binary reports `supportsVision: false` on iOS 26 and `true` on iOS 27.
///
/// Generated class from Pigeon that represents data sent in messages.
struct LocalAiBackendInfo: Hashable {
  var backend: LocalAiBackend
  var platform: String
  var apiName: String
  /// Native function calling (Apple `Tool`). False where tool use has to be
  /// woven into the prompt instead.
  var supportsToolCalling: Bool
  /// Generation constrained to a JSON schema (Apple `GenerationSchema`,
  /// Chrome's `responseConstraint`).
  var supportsStructuredOutput: Bool
  var supportsVision: Bool
  /// A real tokenizer is reachable, so `countTokens` is exact rather than a
  /// character heuristic.
  var supportsTokenCount: Bool
  var supportsModelDownload: Bool
  var supportsPlayStoreRedirect: Bool
  /// The backend is present AND this build can drive it.
  var isConfigured: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LocalAiBackendInfo? {
    let backend = pigeonVar_list[0] as! LocalAiBackend
    let platform = pigeonVar_list[1] as! String
    let apiName = pigeonVar_list[2] as! String
    let supportsToolCalling = pigeonVar_list[3] as! Bool
    let supportsStructuredOutput = pigeonVar_list[4] as! Bool
    let supportsVision = pigeonVar_list[5] as! Bool
    let supportsTokenCount = pigeonVar_list[6] as! Bool
    let supportsModelDownload = pigeonVar_list[7] as! Bool
    let supportsPlayStoreRedirect = pigeonVar_list[8] as! Bool
    let isConfigured = pigeonVar_list[9] as! Bool

    return LocalAiBackendInfo(
      backend: backend,
      platform: platform,
      apiName: apiName,
      supportsToolCalling: supportsToolCalling,
      supportsStructuredOutput: supportsStructuredOutput,
      supportsVision: supportsVision,
      supportsTokenCount: supportsTokenCount,
      supportsModelDownload: supportsModelDownload,
      supportsPlayStoreRedirect: supportsPlayStoreRedirect,
      isConfigured: isConfigured
    )
  }
  func toList() -> [Any?] {
    return [
      backend,
      platform,
      apiName,
      supportsToolCalling,
      supportsStructuredOutput,
      supportsVision,
      supportsTokenCount,
      supportsModelDownload,
      supportsPlayStoreRedirect,
      isConfigured,
    ]
  }
  static func == (lhs: LocalAiBackendInfo, rhs: LocalAiBackendInfo) -> Bool {
    return deepEqualsLocalAiPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashLocalAiPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ToolParameterSpec: Hashable {
  var name: String
  var kind: ToolArgumentKind
  var optional: Bool
  var description: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ToolParameterSpec? {
    let name = pigeonVar_list[0] as! String
    let kind = pigeonVar_list[1] as! ToolArgumentKind
    let optional = pigeonVar_list[2] as! Bool
    let description: String? = nilOrValue(pigeonVar_list[3])

    return ToolParameterSpec(
      name: name,
      kind: kind,
      optional: optional,
      description: description
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      kind,
      optional,
      description,
    ]
  }
  static func == (lhs: ToolParameterSpec, rhs: ToolParameterSpec) -> Bool {
    return deepEqualsLocalAiPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashLocalAiPigeon(value: toList(), hasher: &hasher)
  }
}

/// Per-call sampling overrides.
///
/// A session fixes its sampling at creation, which is what flutter_gemma's
/// engine contract expects. Both Apple `respond(options:)` and ML Kit's
/// request builder also accept options per request, though, and the
/// prompt-oriented Dart API applies a `GenerationConfig` to a single call
/// without disturbing the conversation. Every field is nullable: null means
/// "keep what the session was created with".
///
/// Generated class from Pigeon that represents data sent in messages.
struct GenerationOverrides: Hashable {
  var temperature: Double? = nil
  var topP: Double? = nil
  var topK: Int64? = nil
  var maxOutputTokens: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GenerationOverrides? {
    let temperature: Double? = nilOrValue(pigeonVar_list[0])
    let topP: Double? = nilOrValue(pigeonVar_list[1])
    let topK: Int64? = nilOrValue(pigeonVar_list[2])
    let maxOutputTokens: Int64? = nilOrValue(pigeonVar_list[3])

    return GenerationOverrides(
      temperature: temperature,
      topP: topP,
      topK: topK,
      maxOutputTokens: maxOutputTokens
    )
  }
  func toList() -> [Any?] {
    return [
      temperature,
      topP,
      topK,
      maxOutputTokens,
    ]
  }
  static func == (lhs: GenerationOverrides, rhs: GenerationOverrides) -> Bool {
    return deepEqualsLocalAiPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashLocalAiPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ToolSpec: Hashable {
  var name: String
  var description: String
  var parameters: [ToolParameterSpec]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ToolSpec? {
    let name = pigeonVar_list[0] as! String
    let description = pigeonVar_list[1] as! String
    let parameters = pigeonVar_list[2] as! [ToolParameterSpec]

    return ToolSpec(
      name: name,
      description: description,
      parameters: parameters
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      description,
      parameters,
    ]
  }
  static func == (lhs: ToolSpec, rhs: ToolSpec) -> Bool {
    return deepEqualsLocalAiPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashLocalAiPigeon(value: toList(), hasher: &hasher)
  }
}

private class LocalAiPigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AvailabilityStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return LocalAiBackend(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ToolArgumentKind(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return LocalAiBackendInfo.fromList(self.readValue() as! [Any?])
    case 133:
      return ToolParameterSpec.fromList(self.readValue() as! [Any?])
    case 134:
      return GenerationOverrides.fromList(self.readValue() as! [Any?])
    case 135:
      return ToolSpec.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class LocalAiPigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AvailabilityStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? LocalAiBackend {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? ToolArgumentKind {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? LocalAiBackendInfo {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? ToolParameterSpec {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? GenerationOverrides {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? ToolSpec {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class LocalAiPigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return LocalAiPigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return LocalAiPigeonPigeonCodecWriter(data: data)
  }
}

class LocalAiPigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = LocalAiPigeonPigeonCodec(readerWriter: LocalAiPigeonPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LocalAiService {
  func checkAvailability(completion: @escaping (Result<AvailabilityStatus, Error>) -> Void)
  /// One human-readable sentence naming what the user would have to change —
  /// enable Apple Intelligence, update the OS, use an eligible device. Shown
  /// in UI, so it is prose, not a status code.
  func availabilityReason(completion: @escaping (Result<String, Error>) -> Void)
  func getBackendInfo(completion: @escaping (Result<LocalAiBackendInfo, Error>) -> Void)
  /// Starts the OS feature download (AICore). Progress arrives on the event
  /// channel as `{code: DOWNLOAD_PROGRESS, bytesDownloaded, bytesTotal}`.
  /// No-op on darwin, where readiness is user-controlled in Settings.
  func downloadFeature(completion: @escaping (Result<Void, Error>) -> Void)
  /// Opens Google AICore in the Play Store. False on every non-Android host.
  func openAICorePlayStore(completion: @escaping (Result<Bool, Error>) -> Void)
  func createModel(supportImage: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  func closeModel(completion: @escaping (Result<Void, Error>) -> Void)
  /// Sessions are keyed by a caller-allocated [sessionId]; every generated
  /// token on the event channel carries it back so concurrent sessions can be
  /// demultiplexed.
  ///
  /// [tools] must be supplied here rather than per-request: Apple binds tools
  /// at `LanguageModelSession` construction and cannot add them to a live
  /// session.
  func createSession(sessionId: Int64, temperature: Double, topK: Int64, topP: Double?, maxOutputTokens: Int64?, systemInstruction: String?, tools: [ToolSpec]?, completion: @escaping (Result<Void, Error>) -> Void)
  func closeSession(sessionId: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func addQueryChunk(sessionId: Int64, text: String, completion: @escaping (Result<Void, Error>) -> Void)
  func addImage(sessionId: Int64, imageBytes: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  func generateResponse(sessionId: Int64, overrides: GenerationOverrides?, completion: @escaping (Result<String, Error>) -> Void)
  /// Streams the response; tokens arrive on the event channel as
  /// `{sessionId, partialResult, done}` and failures as
  /// `{sessionId, code: ERROR, message}`.
  func generateResponseAsync(sessionId: Int64, overrides: GenerationOverrides?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Generation constrained to [schemaJson] (a JSON Schema document). Hosts
  /// reporting `supportsStructuredOutput: false` fail this call rather than
  /// silently returning prose.
  func generateStructuredResponse(sessionId: Int64, schemaJson: String, overrides: GenerationOverrides?, completion: @escaping (Result<String, Error>) -> Void)
  func stopGeneration(sessionId: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  /// Exact token count where the host has a tokenizer. Hosts reporting
  /// `supportsTokenCount: false` fail with `TOKENIZER_UNAVAILABLE`, which the
  /// Dart layer turns into a documented character-based estimate.
  func countTokens(text: String, completion: @escaping (Result<Int64, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LocalAiServiceSetup {
  static var codec: FlutterStandardMessageCodec { LocalAiPigeonPigeonCodec.shared }
  /// Sets up an instance of `LocalAiService` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LocalAiService?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let checkAvailabilityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_local_ai.LocalAiService.checkAvailability\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkAvailabilityChannel.setMessageHandler { _, reply in
        api.checkAvailability { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      checkAvailabilityChannel.setMessageHandler(nil)
    }
    /// One human-readable sentence naming what the user would have to change —
    /// enable Apple Intelligence, update the OS, use an eligible device. Shown
    /// in UI, so it is prose, not a status code.
    let availabilityReasonChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_local_ai.LocalAiService.availabilityReason\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      availabilityReasonChannel.setMessageHandler { _, reply in
        api.availabilityReason { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      availabilityReasonChannel.setMessageHandler(nil)
    }
    let getBackendInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_local_ai.LocalAiService.getBackendInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBackendInfoChannel.setMessageHandler { _, reply in
        api.getBackendInfo { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getBackendInfoChannel.setMessageHandler(nil)
    }
    /// Starts the OS feature download (AICore). Progress arrives on the event
    /// channel as `{code: DOWNLOAD_PROGRESS, bytesDownloaded, bytesTotal}`.
    /// No-op on darwin, where readiness is user-controlled in Settings.
    let downloadFeatureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_local_ai.LocalAiService.downloadFeature\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      downloadFeatureChannel.setMessageHandler { _, reply in
        api.downloadFeature { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      downloadFeatureChannel.setMessageHandler(nil)
    }
    /// Opens Google AICore in the Play Store. False on every non-Android host.
    let openAICorePlayStoreChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_local_ai.LocalAiService.openAICorePlayStore\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openAICorePlayStoreChannel.setMessageHandler { _, reply in
        api.openAICorePlayStore { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openAICorePlayStoreChannel.setMessageHandler(nil)
    }
    let createModelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_local_ai.LocalAiService.createModel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createModelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let supportImageArg = args[0] as! Bool
        api.createModel(supportImage: supportImageArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createModelChannel.setMessageHandler(nil)
    }
    let closeModelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_local_ai.LocalAiService.closeModel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeModelChannel.setMessageHandler { _, reply in
        api.closeModel { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeModelChannel.setMessageHandler(nil)
    }
    /// Sessions are keyed by a caller-allocated [sessionId]; every generated
    /// token on the event channel carries it back so concurrent sessions can be
    /// demultiplexed.
    ///
    /// [tools] must be supplied here rather than per-request: Apple binds tools
    /// at `LanguageModelSession` construction and cannot add them to a live
    /// session.
    let createSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_local_ai.LocalAiService.createSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let temperatureArg = args[1] as! Double
        let topKArg = args[2] as! Int64
        let topPArg: Double? = nilOrValue(args[3])
        let maxOutputTokensArg: Int64? = nilOrValue(args[4])
        let systemInstructionArg: String? = nilOrValue(args[5])
        let toolsArg: [ToolSpec]? = nilOrValue(args[6])
        api.createSession(sessionId: sessionIdArg, temperature: temperatureArg, topK: topKArg, topP: topPArg, maxOutputTokens: maxOutputTokensArg, systemInstruction: systemInstructionArg, tools: toolsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createSessionChannel.setMessageHandler(nil)
    }
    let closeSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_local_ai.LocalAiService.closeSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        api.closeSession(sessionId: sessionIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeSessionChannel.setMessageHandler(nil)
    }
    let addQueryChunkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_local_ai.LocalAiService.addQueryChunk\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addQueryChunkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let textArg = args[1] as! String
        api.addQueryChunk(sessionId: sessionIdArg, text: textArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addQueryChunkChannel.setMessageHandler(nil)
    }
    let addImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_local_ai.LocalAiService.addImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let imageBytesArg = args[1] as! FlutterStandardTypedData
        api.addImage(sessionId: sessionIdArg, imageBytes: imageBytesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addImageChannel.setMessageHandler(nil)
    }
    let generateResponseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_local_ai.LocalAiService.generateResponse\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateResponseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let overridesArg: GenerationOverrides? = nilOrValue(args[1])
        api.generateResponse(sessionId: sessionIdArg, overrides: overridesArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateResponseChannel.setMessageHandler(nil)
    }
    /// Streams the response; tokens arrive on the event channel as
    /// `{sessionId, partialResult, done}` and failures as
    /// `{sessionId, code: ERROR, message}`.
    let generateResponseAsyncChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_local_ai.LocalAiService.generateResponseAsync\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateResponseAsyncChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let overridesArg: GenerationOverrides? = nilOrValue(args[1])
        api.generateResponseAsync(sessionId: sessionIdArg, overrides: overridesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateResponseAsyncChannel.setMessageHandler(nil)
    }
    /// Generation constrained to [schemaJson] (a JSON Schema document). Hosts
    /// reporting `supportsStructuredOutput: false` fail this call rather than
    /// silently returning prose.
    let generateStructuredResponseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_local_ai.LocalAiService.generateStructuredResponse\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateStructuredResponseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let schemaJsonArg = args[1] as! String
        let overridesArg: GenerationOverrides? = nilOrValue(args[2])
        api.generateStructuredResponse(sessionId: sessionIdArg, schemaJson: schemaJsonArg, overrides: overridesArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateStructuredResponseChannel.setMessageHandler(nil)
    }
    let stopGenerationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_local_ai.LocalAiService.stopGeneration\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopGenerationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        api.stopGeneration(sessionId: sessionIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopGenerationChannel.setMessageHandler(nil)
    }
    /// Exact token count where the host has a tokenizer. Hosts reporting
    /// `supportsTokenCount: false` fail with `TOKENIZER_UNAVAILABLE`, which the
    /// Dart layer turns into a documented character-based estimate.
    let countTokensChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_local_ai.LocalAiService.countTokens\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      countTokensChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let textArg = args[0] as! String
        api.countTokens(text: textArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      countTokensChannel.setMessageHandler(nil)
    }
  }
}
/// Host → Dart callback for native tool calling. The host suspends generation,
/// asks Dart to run the tool, and feeds the result back to the model.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol LocalAiToolRunnerProtocol {
  /// [argumentsJson] is a JSON object of the arguments the model produced.
  /// Returns the tool's result encoded as JSON, or null when the tool yields
  /// nothing.
  func onToolCall(sessionId sessionIdArg: Int64, toolName toolNameArg: String, argumentsJson argumentsJsonArg: String, completion: @escaping (Result<String?, PigeonError>) -> Void)
}
class LocalAiToolRunner: LocalAiToolRunnerProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: LocalAiPigeonPigeonCodec {
    return LocalAiPigeonPigeonCodec.shared
  }
  /// [argumentsJson] is a JSON object of the arguments the model produced.
  /// Returns the tool's result encoded as JSON, or null when the tool yields
  /// nothing.
  func onToolCall(sessionId sessionIdArg: Int64, toolName toolNameArg: String, argumentsJson argumentsJsonArg: String, completion: @escaping (Result<String?, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_local_ai.LocalAiToolRunner.onToolCall\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([sessionIdArg, toolNameArg, argumentsJsonArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        let result: String? = nilOrValue(listResponse[0])
        completion(.success(result))
      }
    }
  }
}
