// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.vezz.flutter_local_ai

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object LocalAiPigeonPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Availability of the OS built-in model. Mirrors
 * `flutter_gemma_builtin_ai`'s `AvailabilityStatus` one-to-one so the bridge
 * can map it across without a lookup table.
 */
enum class AvailabilityStatus(val raw: Int) {
  AVAILABLE(0),
  DOWNLOADABLE(1),
  DOWNLOADING(2),
  UNAVAILABLE_DEVICE_UNSUPPORTED(3),
  UNAVAILABLE_OS_TOO_OLD(4),
  /**
   * The feature exists but the user turned it off — Apple Intelligence in
   * Settings, or the AICore/Gemini Nano toggle on Android.
   */
  UNAVAILABLE_DISABLED(5),
  UNAVAILABLE_OTHER(6);

  companion object {
    fun ofRaw(raw: Int): AvailabilityStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Which OS API is answering. `unsupported` is the honest answer on a platform
 * with no built-in model rather than a guess.
 */
enum class LocalAiBackend(val raw: Int) {
  ANDROID_ML_KIT_GEN_AI(0),
  APPLE_FOUNDATION_MODELS(1),
  WINDOWS_AI_FOUNDRY(2),
  /**
   * Windows AI Foundry is present but the plugin was built without the
   * Windows AI SDK headers, so no inference can run.
   */
  WINDOWS_AI_FOUNDRY_UNCONFIGURED(3),
  CHROME_PROMPT_API(4),
  UNSUPPORTED(5);

  companion object {
    fun ofRaw(raw: Int): LocalAiBackend? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ToolArgumentKind(val raw: Int) {
  STRING(0),
  INTEGER(1),
  NUMBER(2),
  BOOLEAN(3);

  companion object {
    fun ofRaw(raw: Int): ToolArgumentKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * What the *running* host can actually do. Every field is a runtime property
 * of this device + OS + build, never a compile-time assumption: the same
 * binary reports `supportsVision: false` on iOS 26 and `true` on iOS 27.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LocalAiBackendInfo (
  val backend: LocalAiBackend,
  val platform: String,
  val apiName: String,
  /**
   * Native function calling (Apple `Tool`). False where tool use has to be
   * woven into the prompt instead.
   */
  val supportsToolCalling: Boolean,
  /**
   * Generation constrained to a JSON schema (Apple `GenerationSchema`,
   * Chrome's `responseConstraint`).
   */
  val supportsStructuredOutput: Boolean,
  val supportsVision: Boolean,
  /**
   * A real tokenizer is reachable, so `countTokens` is exact rather than a
   * character heuristic.
   */
  val supportsTokenCount: Boolean,
  val supportsModelDownload: Boolean,
  val supportsPlayStoreRedirect: Boolean,
  /** The backend is present AND this build can drive it. */
  val isConfigured: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LocalAiBackendInfo {
      val backend = pigeonVar_list[0] as LocalAiBackend
      val platform = pigeonVar_list[1] as String
      val apiName = pigeonVar_list[2] as String
      val supportsToolCalling = pigeonVar_list[3] as Boolean
      val supportsStructuredOutput = pigeonVar_list[4] as Boolean
      val supportsVision = pigeonVar_list[5] as Boolean
      val supportsTokenCount = pigeonVar_list[6] as Boolean
      val supportsModelDownload = pigeonVar_list[7] as Boolean
      val supportsPlayStoreRedirect = pigeonVar_list[8] as Boolean
      val isConfigured = pigeonVar_list[9] as Boolean
      return LocalAiBackendInfo(backend, platform, apiName, supportsToolCalling, supportsStructuredOutput, supportsVision, supportsTokenCount, supportsModelDownload, supportsPlayStoreRedirect, isConfigured)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      backend,
      platform,
      apiName,
      supportsToolCalling,
      supportsStructuredOutput,
      supportsVision,
      supportsTokenCount,
      supportsModelDownload,
      supportsPlayStoreRedirect,
      isConfigured,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LocalAiBackendInfo) {
      return false
    }
    if (this === other) {
      return true
    }
    return LocalAiPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ToolParameterSpec (
  val name: String,
  val kind: ToolArgumentKind,
  val optional: Boolean,
  val description: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ToolParameterSpec {
      val name = pigeonVar_list[0] as String
      val kind = pigeonVar_list[1] as ToolArgumentKind
      val optional = pigeonVar_list[2] as Boolean
      val description = pigeonVar_list[3] as String?
      return ToolParameterSpec(name, kind, optional, description)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      kind,
      optional,
      description,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ToolParameterSpec) {
      return false
    }
    if (this === other) {
      return true
    }
    return LocalAiPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ToolSpec (
  val name: String,
  val description: String,
  val parameters: List<ToolParameterSpec>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ToolSpec {
      val name = pigeonVar_list[0] as String
      val description = pigeonVar_list[1] as String
      val parameters = pigeonVar_list[2] as List<ToolParameterSpec>
      return ToolSpec(name, description, parameters)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      description,
      parameters,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ToolSpec) {
      return false
    }
    if (this === other) {
      return true
    }
    return LocalAiPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class LocalAiPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AvailabilityStatus.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          LocalAiBackend.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ToolArgumentKind.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LocalAiBackendInfo.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ToolParameterSpec.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ToolSpec.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AvailabilityStatus -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is LocalAiBackend -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is ToolArgumentKind -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is LocalAiBackendInfo -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ToolParameterSpec -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is ToolSpec -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface LocalAiService {
  fun checkAvailability(callback: (Result<AvailabilityStatus>) -> Unit)
  /**
   * One human-readable sentence naming what the user would have to change —
   * enable Apple Intelligence, update the OS, use an eligible device. Shown
   * in UI, so it is prose, not a status code.
   */
  fun availabilityReason(callback: (Result<String>) -> Unit)
  fun getBackendInfo(callback: (Result<LocalAiBackendInfo>) -> Unit)
  /**
   * Starts the OS feature download (AICore). Progress arrives on the event
   * channel as `{code: DOWNLOAD_PROGRESS, bytesDownloaded, bytesTotal}`.
   * No-op on darwin, where readiness is user-controlled in Settings.
   */
  fun downloadFeature(callback: (Result<Unit>) -> Unit)
  /** Opens Google AICore in the Play Store. False on every non-Android host. */
  fun openAICorePlayStore(callback: (Result<Boolean>) -> Unit)
  fun createModel(supportImage: Boolean, callback: (Result<Unit>) -> Unit)
  fun closeModel(callback: (Result<Unit>) -> Unit)
  /**
   * Sessions are keyed by a caller-allocated [sessionId]; every generated
   * token on the event channel carries it back so concurrent sessions can be
   * demultiplexed.
   *
   * [tools] must be supplied here rather than per-request: Apple binds tools
   * at `LanguageModelSession` construction and cannot add them to a live
   * session.
   */
  fun createSession(sessionId: Long, temperature: Double, topK: Long, topP: Double?, maxOutputTokens: Long?, systemInstruction: String?, tools: List<ToolSpec>?, callback: (Result<Unit>) -> Unit)
  fun closeSession(sessionId: Long, callback: (Result<Unit>) -> Unit)
  fun addQueryChunk(sessionId: Long, text: String, callback: (Result<Unit>) -> Unit)
  fun addImage(sessionId: Long, imageBytes: ByteArray, callback: (Result<Unit>) -> Unit)
  fun generateResponse(sessionId: Long, callback: (Result<String>) -> Unit)
  /**
   * Streams the response; tokens arrive on the event channel as
   * `{sessionId, partialResult, done}` and failures as
   * `{sessionId, code: ERROR, message}`.
   */
  fun generateResponseAsync(sessionId: Long, callback: (Result<Unit>) -> Unit)
  /**
   * Generation constrained to [schemaJson] (a JSON Schema document). Hosts
   * reporting `supportsStructuredOutput: false` fail this call rather than
   * silently returning prose.
   */
  fun generateStructuredResponse(sessionId: Long, schemaJson: String, callback: (Result<String>) -> Unit)
  fun stopGeneration(sessionId: Long, callback: (Result<Unit>) -> Unit)
  /**
   * Exact token count where the host has a tokenizer. Hosts reporting
   * `supportsTokenCount: false` fail with `TOKENIZER_UNAVAILABLE`, which the
   * Dart layer turns into a documented character-based estimate.
   */
  fun countTokens(text: String, callback: (Result<Long>) -> Unit)

  companion object {
    /** The codec used by LocalAiService. */
    val codec: MessageCodec<Any?> by lazy {
      LocalAiPigeonPigeonCodec()
    }
    /** Sets up an instance of `LocalAiService` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LocalAiService?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.checkAvailability$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.checkAvailability{ result: Result<AvailabilityStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LocalAiPigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LocalAiPigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.availabilityReason$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.availabilityReason{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LocalAiPigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LocalAiPigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.getBackendInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getBackendInfo{ result: Result<LocalAiBackendInfo> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LocalAiPigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LocalAiPigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.downloadFeature$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.downloadFeature{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LocalAiPigeonPigeonUtils.wrapError(error))
              } else {
                reply.reply(LocalAiPigeonPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.openAICorePlayStore$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.openAICorePlayStore{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LocalAiPigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LocalAiPigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.createModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val supportImageArg = args[0] as Boolean
            api.createModel(supportImageArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LocalAiPigeonPigeonUtils.wrapError(error))
              } else {
                reply.reply(LocalAiPigeonPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.closeModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.closeModel{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LocalAiPigeonPigeonUtils.wrapError(error))
              } else {
                reply.reply(LocalAiPigeonPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.createSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            val temperatureArg = args[1] as Double
            val topKArg = args[2] as Long
            val topPArg = args[3] as Double?
            val maxOutputTokensArg = args[4] as Long?
            val systemInstructionArg = args[5] as String?
            val toolsArg = args[6] as List<ToolSpec>?
            api.createSession(sessionIdArg, temperatureArg, topKArg, topPArg, maxOutputTokensArg, systemInstructionArg, toolsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LocalAiPigeonPigeonUtils.wrapError(error))
              } else {
                reply.reply(LocalAiPigeonPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.closeSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            api.closeSession(sessionIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LocalAiPigeonPigeonUtils.wrapError(error))
              } else {
                reply.reply(LocalAiPigeonPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.addQueryChunk$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            val textArg = args[1] as String
            api.addQueryChunk(sessionIdArg, textArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LocalAiPigeonPigeonUtils.wrapError(error))
              } else {
                reply.reply(LocalAiPigeonPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.addImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            val imageBytesArg = args[1] as ByteArray
            api.addImage(sessionIdArg, imageBytesArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LocalAiPigeonPigeonUtils.wrapError(error))
              } else {
                reply.reply(LocalAiPigeonPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.generateResponse$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            api.generateResponse(sessionIdArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LocalAiPigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LocalAiPigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.generateResponseAsync$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            api.generateResponseAsync(sessionIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LocalAiPigeonPigeonUtils.wrapError(error))
              } else {
                reply.reply(LocalAiPigeonPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.generateStructuredResponse$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            val schemaJsonArg = args[1] as String
            api.generateStructuredResponse(sessionIdArg, schemaJsonArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LocalAiPigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LocalAiPigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.stopGeneration$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            api.stopGeneration(sessionIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LocalAiPigeonPigeonUtils.wrapError(error))
              } else {
                reply.reply(LocalAiPigeonPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_local_ai.LocalAiService.countTokens$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textArg = args[0] as String
            api.countTokens(textArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LocalAiPigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LocalAiPigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Host → Dart callback for native tool calling. The host suspends generation,
 * asks Dart to run the tool, and feeds the result back to the model.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class LocalAiToolRunner(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by LocalAiToolRunner. */
    val codec: MessageCodec<Any?> by lazy {
      LocalAiPigeonPigeonCodec()
    }
  }
  /**
   * [argumentsJson] is a JSON object of the arguments the model produced.
   * Returns the tool's result encoded as JSON, or null when the tool yields
   * nothing.
   */
  fun onToolCall(sessionIdArg: Long, toolNameArg: String, argumentsJsonArg: String, callback: (Result<String?>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_local_ai.LocalAiToolRunner.onToolCall$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(sessionIdArg, toolNameArg, argumentsJsonArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          val output = it[0] as String?
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(LocalAiPigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
